### ISSUE TITLE
Could not compile v1.1.0

### ISSUE THREAD

**Issue by jyp** [habeanf/yap#1]
Trying to compile v1.1.0 yielded the error message:

```
go/src/yap/nlp/format/taggedsentence/sent.go:46: too few values in struct initializer
go/src/yap/nlp/format/taggedsentence/sent.go:47: too few values in struct initializer
```

Any idea what is happening? Should I be using another version?

**Comment by habeanf** [comment]
It is a warning, you may disregard it.

**Comment by habeanf** [comment]
Fixed in https://github.com/habeanf/yap/commit/d71d8d11a82e7786cf8fecc6a0b760d4ca8eb130 release v1.2.0
