### ISSUE TITLE
Status of the SPMRL⥋UD clitics morphological disambiguation issue ― identified in the CoNLL-2017 Shared Task

### ISSUE THREAD

**Issue by matanox** [habeanf/yap#3]
Hi,

Might you comment on the status of the second "bug" described in [the CoNLL-2017 submission article](http://www.aclweb.org/anthology/K17-3027), the one relating to expecting clitics to be represented as per the SPMRL convention rather than the Universal Dependencies one? Actually I'd not necessarily call it a bug, but a standards support aspect, but as long as the repo implies very standard Universal Dependencies as a source format, I'll accede to the exacting "bug" status implied in the article.

Was the code ultimately modified to assume clitics as separate syntactic elements, as implied in the article, or did the temporary remedy described therein in the article persist? or did you actually enable all of the modes as runtime options? (the three options possibly being dubbed SPMRL, UD with special out-of-standard indication, and something like strict UD).

Thanks for commenting!!

**Comment by habeanf** [comment]
In commit 7a89b37 I added a parameter function (the MD projection in the paper) that modifies clitics. There is a command line option to select a parameter function, so I guess the answer is UD with a special out-of-standard indication.
