### ISSUE TITLE
Single sentence file may not process successfully 

### ISSUE THREAD

**Issue by matanox** [habeanf/yap#5]
Somewhere between a question and an issue ―
If an input file (`input.raw`) contains only a single sentence, e.g.:

```
עשרות
אנשים
מגיעים
מתאילנד

```

Then no tokens seem to go detected and the output file is empty, when running:

```
./yap hebma -raw input.raw -out lattices.conll
```

In further experimentation it may seem like the first sentence may get ignored, or some other irregularity causing this. Thing is this is the classical scenario for trying a single sentence, unless there's also an interactive mode aside requiring file input. 

Thanks in advance for your commenting!

**Comment by matanox** [comment]
BTW the demo at http://onlp.openu.org.il might seem to be down...

**Comment by habeanf** [comment]
You need to add an empty line after the last word. There should be two newlines at the end of a sentence.
Regarding onlp.openu.org.il, you should discuss with @rtsarfaty or @aseker00

**Comment by matanox** [comment]
Doh, it was https://github.com/atom/atom/issues/3969
Must have been really late at night...

**Comment by matanox** [comment]
Will do.
