### ISSUE TITLE
restart api

### ISSUE THREAD

**Issue by yishairasowsky** [habeanf/yap#8]
great work you have done the api! i just have trouble when it disconnects... is there a way to make it automatically reconnect, instead of me having to type `src/yap/./yap api`?

**Comment by yishairasowsky** [comment]
btw the reason it stops is seemingly because there are some sentences that are not readable by yap... maybe they have funny characters. should i clean them first and only then parse? or maybe you have another insight, such as, which types of words or sentences cannot be parsed by yap? thanks!

**Comment by yishairasowsky** [comment]
@habeanf @mikelibg @rtsarfaty love your work

**Comment by habeanf** [comment]
This repository is no longer maintained. Please use https://github.com/onlplab/yap
