### ISSUE TITLE
changing api port

### ISSUE THREAD

**Issue by AmirBialer** [habeanf/yap#9]
I am writing here since the new yap git doesn't have an "issues" tab:
I want to run YAP api in multiple process- so I want so assign each process to a different port-
where in the code is the port address? (":8000")
thanks!

**Comment by habeanf** [comment]
I doubt anyone but me will see this, so I'll do my best to answer. I'm assuming you're referring to the "webapi" functionality that was added by @aseker00 a few years ago. Looking at the code in the onlp fork, I think this is what you're looking for:
https://github.com/OnlpLab/yap/blame/master/webapi/webapi.go#L172
Refactoring the string ":8000" into a flag should be fairly straightforward

**Comment by AmirBialer** [comment]
thanks for the answer!
when I searched the complete code I found more mentions of 8000 and I weren't sure if they are related with the docker or the webapi as you mentioned.

anyways I tried what what you suggested and it didn't work for me- but I'm not sure if the port was busy or it's not that simple.
